Test Success before like api
wafflestudio18-5/team6-server pull request #15
Opened 2021-01-02 11:55 UTC by Noaarhk

- userserializer 중복코드 수정
- article 작성 수정 조회 삭제 기능 확인
- like 와 comment 작업 필요

2021-01-02 13:21 UTC, sanggggg requested changes

2021-01-02 13:21 UTC, sanggggg commented on CarrotMarket/village/serializers.py
> +    @transaction.atomic
[nitpick]
atomic 필요 없을 것 같습니다

2021-01-02 13:21 UTC, sanggggg commented
말고는 다 좋은 것 같아요~

2021-01-02 14:28 UTC, kmy17518 approved these changes
댓글 남긴거 하나만 확인해주세요!! 저 부분만 문제 없으면 다 좋은 것 같습니다~

2021-01-02 14:28 UTC, kmy17518 commented on CarrotMarket/user/serializers.py
> -        return UserProfileSerializer(user.userprofile, context=self.context).data #여기서 오류 AttributeError: 'collections.OrderedDict' object has no attribute 'userprofile' 넘겨주는 값 잘못되었
UserSerializer에 area랑 nickname phone 없어도 유저 생성 되는지 혹시 확인해 보셨나요?ㅠㅠ저번에 저 부분 추가한 이유가 포스트맨으로 바디에 area, nickname, phone 을 포함해서 유저 생성 request 보냈을 때 AttributeError떠서 그런 거였거든요ㅠㅠ(사실 이론상은 없어도 정상적으로 작동해야 하는거 같은데...) 만약 저 부분 없어도 정상적으로 작동하는거 확인하셨으면 저는 다 좋은 것 같습니다!

2021-01-02 15:13 UTC, cs71107 reviewed
LGTM

2021-01-02 15:14 UTC, cs71107 approved these changes
LGTM

2021-01-02 15:28 UTC, Noaarhk commented on CarrotMarket/user/serializers.py
> -        return UserProfileSerializer(user.userprofile, context=self.context).data #여기서 오류 AttributeError: 'collections.OrderedDict' object has no attribute 'userprofile' 넘겨주는 값 잘못되었
확인하면서 수정한건데 내일 다시한번 확인해보고 말씀드릴께요👍

2021-01-03 01:33 UTC, sanggggg approved these changes

2021-01-03 02:16 UTC, merged