create views.py serializers.py
wafflestudio18-5/team6-server pull request #3
Opened 2020-12-23 13:31 UTC by kmy17518

post /user/
put /user/login/
put /user/me/
get/user/{user_id}/

온도 삭제, 소셜로그인, 위치인증 추가 예정

2020-12-23 14:59 UTC, davin111 reviewed
.DS_Store 남는 거 보니까 MacOS 사용하시는 것 같은데, 해당 파일들은 지우고 .gitignore 에도 추가하도록 합시다.

2020-12-23 14:59 UTC, davin111 commented on CarrotMarket/user/serializers.py
> +        Token.objects.create(user=user)
area, kindness, nickname, phone 각각에 대해 굳이 뭘 체크하거나 처리하는 것도 없는데 이걸 각각 변수에 저장해서 UserProfile에게 넘겨주는 부분이 지나치게 긴 거 같네요.

앞에서 validate가 잘 되었다는 전제 하에 `UserProfile.objects.create(**validated_data)` 한 줄이면 될 거 같네요. 이렇게만 고쳐도 좋을 듯.

2020-12-23 14:59 UTC, davin111 commented on CarrotMarket/user/serializers.py
> +        if area is not None or nickname is not None or phone is not None or kindness:
이 부분은 update()를 굳이 overriding 할 필요가 있는지 의문인데, partial=True 로 serializer로 model을 update할 때의 동작을 잘 이해하고 나면, 전혀 이렇게 직접 정의할 필요가 없다는 것을 깨달을 수도 있습니다.

2020-12-23 14:59 UTC, davin111 commented on CarrotMarket/user/serializers.py
> +        super(UserSerializer, self).update(user, validated_data)
앞에 return 을 붙여주어야 온전하게 이 method를 overriding하여 겉에서 보기에 동일한 동작을 보장할 것 같네요.

2020-12-23 14:59 UTC, davin111 commented on CarrotMarket/user/views.py
> +        return Response(serializer.data)X
X?

2020-12-23 14:59 UTC, davin111 commented on CarrotMarket/user/views.py
> +            return Response({"error": "Can't update other Users information"}, status=status.HTTP_403_FORBIDDEN)
403보단 400, 404 같은 것이 더 자연스러울지도?

2020-12-23 15:01 UTC, sanggggg commented on CarrotMarket/user/views.py
> +        return Response(serializer.data)X
!?!

2020-12-24 00:01 UTC, Noaarhk approved these changes
LGTM

2020-12-25 06:16 UTC, sanggggg commented
> .DS_Store 남는 거 보니까 MacOS 사용하시는 것 같은데, 해당 파일들은 지우고 .gitignore 에도 추가하도록 합시다.

#4

2020-12-25 06:18 UTC, sanggggg requested changes
#4 에서 .DS_Store 을 gitignore 에 추가하였으니 반영된 브랜치(main)를 머지해서 ds store 을 없애주세요

2020-12-25 06:18 UTC, sanggggg commented on CarrotMarket/user/views.py
> +        return Response(serializer.data)X
확인해주세요~

2020-12-28 00:19 UTC, Noaarhk approved these changes
LGTM

2020-12-28 00:24 UTC, merged