userserializer가 필요한 부분  제외하고, 일단 구현( userserializer가 필요한 부분 추후 구현 필요)
wafflestudio18-5/team6-server pull request #5
Opened 2020-12-25 00:25 UTC by cs71107

Feed(village) api method 구현( 위치 태그 추가 제외)
위치 태그의 경우 구현에 어려움이 있어, 추후 구현 결정.

2020-12-25 06:15 UTC, sanggggg requested changes

2020-12-25 06:15 UTC, sanggggg commented on CarrotMarket/village/serializers.py
> +        # userserializers need
`# TODO: userserializers need `

처럼 TODO 를 적어두면 ide 에서도 하이라이팅 해줘서 붙여주는걸 추천합니다.

2020-12-25 06:15 UTC, sanggggg commented on CarrotMarket/village/serializers.py
> +            return None
`404` 코드를 돌려줘야하지 않을까요?

2020-12-25 06:15 UTC, sanggggg commented on CarrotMarket/village/views.py
> +            return Response({"error": "title and content cannot be empty."}, status=status.HTTP_400_BAD_REQUEST)
[nitpick]
`"error"` 보다는 `"message"` 라고 적어서 내려주는게 더 적절한 필드명 같아보입니다

2020-12-25 06:15 UTC, sanggggg commented on CarrotMarket/village/views.py
> +        if articles:
```python
if articles.exists():
```
https://medium.com/@bdv111/django%EC%97%90%EC%84%9C-exists-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-b3af4d387930

2020-12-25 06:15 UTC, sanggggg commented on CarrotMarket/village/views.py
> +        if not article
```python
if not article.exists():
```
위와 동일합니다.

2020-12-25 10:55 UTC, kmy17518 approved these changes
혹시 user serializers가 필요한 부분이 현재 있는 UserSerializer 클래스 외에 따로 구현이 필요하신 부분이 있다면 오늘 회의에서 말씀해주세요!!

2020-12-27 14:41 UTC, sanggggg approved these changes
LGTM 🚀

2020-12-28 00:03 UTC, Noaarhk reviewed
변경사항 확인하고 머지시켜주세요!

2020-12-28 04:14 UTC, merged